services:
  monpihole:
    image: pihole/pihole
    ports: 
     - "1080:80"
     - "53:53/udp"
     - "53:53/tcp"

    volumes : 
     - './etc-pihole:/etc/pihole'
     - './etc-dnsmasq.d:/etc/dnsmasq.d'


