FROM nginx:latest
RUN apt --no-cache upgrade && apk add --no-cache bash && apk add --no-cache apache2
COPY nginx.conf /etc/nginx.conf && defaut.conf /etc/nginx/conf.d/
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"] # cette commande permet de garder le programme actif et qu'il ne passe pas en arrière plan une fois qu'elle a démarré.

