services : 
  backend :
    build : 
      context : .
      dockerfile : dockerfile.app
    restart : always
    volumes :
      - ./index.html:/var/www/localhost/htdocs/index.html
    ports :
      - 8090:80


  rev :
    image : nginx:alpine
    volumes : 
      - ./templates:/etc/nginx/templates
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports : 
      - 9080:80
    depends_on : 
      - backend
      - frontend

  frontend :
    build : 
      context : . 
      dockerfile : dockerfile.front
    restart: always
    volumes : 
      - ./index2.html:/var/www/localhost/htdocs/index.html
    ports :
      - 8091:80